const { generateImage } = require('../plugins/imageGenerator');
const { saveSystemLog } = require('../utils/logger');

module.exports = {
    name: 'imagine',
    aliases: ['!imagine', '!img'],
    async execute(sock, msg, chatJid, messageText) {
        let prompt = '';
        if (messageText.toLowerCase().startsWith('!imagine ')) prompt = messageText.slice(9).trim();
        else if (messageText.toLowerCase().startsWith('!img ')) prompt = messageText.slice(5).trim();

        if (!prompt) return await sock.sendMessage(chatJid, { text: '⚠️ Masukkan deskripsi gambar yang ingin dibuat! Contoh: !imagine kota jakarta masa depan, cyberpunk, 4k' }, { quoted: msg });
        
        await sock.sendMessage(chatJid, { text: '🎨 Sedang melukis imajinasi kamu, mohon tunggu sekitar 5-10 detik...' }, { quoted: msg });
        try {
            const imageBuffer = await generateImage(prompt);
            await sock.sendMessage(chatJid, { 
                image: imageBuffer, 
                caption: `✨ *Prompt:* ${prompt}\n_Generated by Bot-Wa AI_` 
            }, { quoted: msg });
            
            await saveSystemLog(chatJid, `User meminta sistem AI Image Generator untuk melukis gambar dengan deskripsi: "${prompt}". Gambar berhasil dikirim ke user.`);
        } catch (err) {
            await sock.sendMessage(chatJid, { text: `❌ ${err.message}` }, { quoted: msg });
        }
    }
};
